### ISSUE TITLE
Harbor robo account key vs password

### ISSUE THREAD

**Issue by lalithvaka** [sysdiglabs/harbor-scanner-sysdig-secure#1]
Just wondering if the inline processing needs to change the robo account password to token as Harbor is not creating passwords for the robo accounts but the Token. 

```
inlineScanning:
  enabled: false
  harbor:
    CA: ""
    robotAccount:
      name: ""
      password: ""
```
